name: rijksmuseum_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  http: ^0.13.3
  mockito: ^5.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4

flutter:

  uses-material-design: true